services: 
    frontend:
        build:
            dockerfile: ./frontend/Dockerfile
        ports:
            - "5173:5173"

    backend:
        build:
            dockerfile: ./backend/Dockerfile
        ports:
            - "5000:5000"
